name: Run Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose up -d --build

      - name: Wait for API to be ready
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: "http://localhost:3003"
          timeout: 90 # tempo limite em segundos para a API subir

      - name: Populate database
        run: |
          docker exec -i db psql -U postgres -d restaurante-delivery < /docker-entrypoint-initdb.d/init.sql
        env:
          PGPASSWORD: 123

      - name: Run Cypress tests
        run: |
          cd testes-api-delivery-cypress
          npm install
          npx cypress run
